name: Deploy

on:
  push:
    branches: [ main ]

permissions:
  contents: read
  id-token: write

jobs:
  deploy-auth:
    runs-on: ubuntu-latest
    environment: auth
    steps:
      - uses: actions/checkout@v4
      - uses: actions/setup-node@v5
        with:
          node-version: 22.x
      - uses: aws-actions/configure-aws-credentials@v4
        with:
          role-to-assume: ${{ secrets.AWS_ROLE_ARN }}
          role-session-name: ${{ github.run_id }}
          aws-region: us-east-2
      - run: npm ci
      - run: npm run cdk deploy TSCSDemoAuthKey
      - run: aws secretsmanager put-secret-value --secret-id tailscale/tscs-demo-auth-key --secret-string "$TS_AUTHKEY"
        env:
          TS_AUTHKEY: ${{ secrets.TS_AUTHKEY }}
  deploy-router:
    needs: [ deploy-auth ]
    runs-on: ubuntu-latest
    strategy:
      matrix:
        region: [ us-east-2 ]
    environment: ${{ matrix.region }}
    steps:
      - uses: actions/checkout@v4
      - uses: actions/setup-node@v5
        with:
          node-version: 22.x
      - uses: aws-actions/configure-aws-credentials@v4
        with:
          role-to-assume: ${{ secrets.AWS_ROLE_ARN }}
          role-session-name: ${{ github.run_id }}
          aws-region: ${{ matrix.region }}
      - run: npm ci
      - run: npm run cdk deploy TSCSDemoNetwork
